import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Techskills from '../content/TechnicalSkills.js'
import WorkExp from '../content/WorkExperience.js'
import Education from '../content/Education.js'
import Hobbies from '../content/Hobbies.js'
import Title from '../components/Title.js'
import Button from '../components/Button.js'
import Menu from '../components/Menu.js'

export default function Home() {
  
  return (
    <div className='container-fluid'>
      <Head>
        <title>Marcio&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main]}>
        <Title tname="Marcio's portfolio" />
        <hr className={['container']} />
        <div className={['container']}>
          <Menu />
        </div>
      </main>
      <footer className={styles.footer}>
        Made by MKI®
      </footer>
    </div>
  )
}