import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Techskills from './menu/TechnicalSkills.js'
import WorkExp from './menu/WorkExperience.js'
import Education from './menu/Education.js'
import Hobbies from './menu/Hobbies.js'
import Title from '/components/Title.js'
import Button from '../components/Button.js'

export default function Home() {
  return (
    <div className='container-fluid'>
      <Head>
        <title>Marcio&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main]}>
        <Title tname="Marcio's portfolio" />
        <hr className={['container']}/>
        <div className={['container']}>
          <div className={'row'}>
            <Button menuName='Technical Skills' selectedmenu={<Techskills />} />
            <Button menuName='Work experience' selectedmenu={<WorkExp />} />
            <Button menuName='Education' selectedmenu={<Education />} />
            <Button menuName='Hobbies' selectedmenu={<Hobbies />} />
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        Made by MKI®
      </footer>
    </div>
  )
}