import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Title from '../components/Title.js'
import Menu from '../components/Menu.js'
import Navbar from '../components/Nav'
import React from 'react';

export default function Home() {
  const [openMenu, setOpenMenu] = React.useState(false);

  return (
    <div className='container-fluid'>
      <Head>
        <title>Marcio&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar openMenu={openMenu} />
      <button className={styles.menuBtn} onClick={() => setOpenMenu(prev => !prev)}>
        <span></span>
      </button>
      <main className={[styles.main]}>
        <Title tname="Marcio's portfolio" />
        <hr className={['container']} />
        <div className={['container']}>
          <Menu />
        </div>
      </main>
      <footer className={styles.footer}>
        Made by Márcio Iwamoto®
      </footer>
    </div>
  )
}